export const INDEX_TAB_PLANIFICACION = 0;
export const INDEX_TAB_GUIA = 1;
export const INDEX_TAB_INFORME = 2;
export const INDEX_TAB_PRIMERA_REVISION = 3;
export const INDEX_TAB_SEGUNDA_REVISION = 4;
export const INDEX_TAB_GDE = 5;

export const ESTADO_AUDITORIA_PLANIFICADA = 1;
export const ESTADO_AUDITORIA_PUBLICADA = 2;
export const ESTADO_AUDITORIA_CANCELADA = 3;
export const ESTADO_GUIA_INICIDADA = 4;
export const ESTADO_GUIA_COMPLETADA = 5;
export const ESTADO_INFORME_INICIADO = 6;
export const ESTADO_INFORME_CONFORMADO = 7;
export const ESTADO_PRIMERA_REVISION_APROBADA = 8;
export const ESTADO_SEGUNDA_REVISION_APROBADA = 9;
export const ESTADO_SEGUNDA_REVISION_OBSERVADA = 10;
export const ESTADO_INFORME_SUBIDO_A_GDE = 11;